spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:sharding.yaml
    url: jdbc:shardingsphere:classpath:sharding-err.yaml